name: atlas_picker
description: "A Flutter package for easy selection of countries and states with customizable pickers."
version: 1.0.2
homepage: https://github.com/fazil-kp/atlas_picker.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.14
  country_flags: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
