name: atlas_picker
description: "A new Flutter package project that provides easy-to-use widgets for selecting countries and states. It allows seamless integration into Flutter apps, offering customizable options to select countries and corresponding states, with support for both flag-only and full country details."
version: 1.0.1
homepage: https://github.com/fazil-kp/atlas_picker.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  build_runner: ^2.4.14
  country_flags: ^3.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
